// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReduceGenderBiasInFeedbackTool.Data;

#nullable disable

namespace ReduceGenderBiasInFeedbackTool.Migrations
{
    [DbContext(typeof(ReduceGenderBiasInFeedbackToolContext))]
    [Migration("20220919195649_info")]
    partial class info
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReduceGenderBiasInFeedbackTool.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBeenChecked")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
